
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author shailasalvatierra
 */
public class jfrmSoporte extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jfrmSoporte.class.getName());

    /**
     * Creates new form jfrmSoporte
     */
    public jfrmSoporte() {
        initComponents();
        this.setSize(500,700);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Partes de la Computadora Christian Duarte");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlblNomPie = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Concepto = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Funcion = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));

        jlblNomPie.setFont(new java.awt.Font("Kannada MN", 1, 24)); // NOI18N
        jlblNomPie.setForeground(new java.awt.Color(255, 255, 255));
        jlblNomPie.setText("Placa Base");

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombres de la Computadora");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/motherboard.png"))); // NOI18N

        Concepto.setForeground(new java.awt.Color(255, 255, 255));
        Concepto.setText("Es el circuito principal de una computadora.");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Concepto:");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Función Principal:");

        Funcion.setForeground(new java.awt.Color(255, 255, 255));
        Funcion.setText("Conectar y coordinar todos los componentes de la computadora.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Concepto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(169, 169, 169)
                                .addComponent(jlblNomPie))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(204, 204, 204)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addComponent(jLabel4)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Funcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblNomPie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Concepto, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Funcion, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Abrir");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Guardar");
        jMenuItem2.addActionListener(this::jMenuItem2ActionPerformed);
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Salir");
        jMenuItem3.addActionListener(this::jMenuItem3ActionPerformed);
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Componentes del PC ");

        jMenuItem4.setText("Placa Base");
        jMenuItem4.addActionListener(this::jMenuItem4ActionPerformed);
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Procesador");
        jMenuItem5.addActionListener(this::jMenuItem5ActionPerformed);
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Memoria RAM");
        jMenuItem6.addActionListener(this::jMenuItem6ActionPerformed);
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Cooler");
        jMenuItem7.addActionListener(this::jMenuItem7ActionPerformed);
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("Fuente de poder");
        jMenuItem8.addActionListener(this::jMenuItem8ActionPerformed);
        jMenu2.add(jMenuItem8);

        jMenuItem11.setText("Tarjeta de Video (GPU");
        jMenuItem11.addActionListener(this::jMenuItem11ActionPerformed);
        jMenu2.add(jMenuItem11);

        jMenuItem12.setText("Tarjeta de Red");
        jMenuItem12.addActionListener(this::jMenuItem12ActionPerformed);
        jMenu2.add(jMenuItem12);

        jMenuItem13.setText("Cooler del Procesador");
        jMenuItem13.addActionListener(this::jMenuItem13ActionPerformed);
        jMenu2.add(jMenuItem13);

        jMenuItem14.setText("Ventilador del Gabinete");
        jMenuItem14.addActionListener(this::jMenuItem14ActionPerformed);
        jMenu2.add(jMenuItem14);

        jMenuItem15.setText("Tarjeta de Sonido");
        jMenuItem15.addActionListener(this::jMenuItem15ActionPerformed);
        jMenu2.add(jMenuItem15);

        jMenuItem16.setText("Bateria CMOS");
        jMenuItem16.addActionListener(this::jMenuItem16ActionPerformed);
        jMenu2.add(jMenuItem16);

        jMenuItem17.setText("Tarjeta SATA");
        jMenuItem17.addActionListener(this::jMenuItem17ActionPerformed);
        jMenu2.add(jMenuItem17);

        jMenuItem18.setText("Cable de Administración");
        jMenuItem18.addActionListener(this::jMenuItem18ActionPerformed);
        jMenu2.add(jMenuItem18);

        jMenuItem19.setText("BIOS/UEFI");
        jMenuItem19.addActionListener(this::jMenuItem19ActionPerformed);
        jMenu2.add(jMenuItem19);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ayuda");

        jMenuItem9.setText("Acerca del programa");
        jMenu3.add(jMenuItem9);

        jMenuItem10.setText("Créditos");
        jMenu3.add(jMenuItem10);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Funcionalidad Abrir");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        jlblNomPie.setText("");
        Concepto.setText("");
        Funcion.setText("");
        jlblNomPie.setText("Cooler");
        Concepto.setText("Es un dispositivo diseñado para disipar el calor y reducir la temperatura.");
        Funcion.setText("Disipar el calor o enfriar");
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cooler.png")));
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        jlblNomPie.setText("");
        Concepto.setText("");
        Funcion.setText("");
        jlblNomPie.setText("Placa Base");
        Concepto.setText("Es el circuito principal de una computadora.");
        Funcion.setText("Conectar y coordinar todos los componentes de la computadora.");
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/motherboard.png")));
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        jlblNomPie.setText("");
        Concepto.setText("");
        Funcion.setText("");
        jlblNomPie.setText("Procesador");
        Concepto.setText("Es el cerebro de la computadora");
        Funcion.setText("Se encarga de interpretar y ejecutar las instrucciones de los programas.");
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cpu.png")));
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        jlblNomPie.setText("");
        Concepto.setText("");
        Funcion.setText("");
        jlblNomPie.setText("Memoria RAM");
        Concepto.setText("Memoria de trabajo a corto plazo de tus dispositivos.");
        Funcion.setText("Almacenar temporalmente datos de los programas que se están usando.");
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ram.png")));
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        jlblNomPie.setText("");
        Concepto.setText("");
        Funcion.setText("");
        jlblNomPie.setText("Fuente de poder");
        Concepto.setText("Dispositivo que convierte la corriente alterna en continua estable.");
        Funcion.setText("Convertir corriente alterna en continua.");
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fuente.png")));
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        int msg=JOptionPane.showConfirmDialog(null, "¿Desea Salir del Software?");
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Funcionalidad Guardar");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        jlblNomPie.setText("");
        Concepto.setText("");
        Funcion.setText("");
        jlblNomPie.setText("Ventilador del Gabinete");
        Concepto.setText("Son componentes encargados de crear un flujo de aire constante dentro de la computadora.");
        Funcion.setText("Mantener una temperatura óptima dentro de la computadora.");
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gab.png")));
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        // TODO add your handling code here:
        jlblNomPie.setText("");
        Concepto.setText("");
        Funcion.setText("");
        jlblNomPie.setText("Tarjeta SATA");
        Concepto.setText("Es un componente de hardware que se conecta a la placa base.");
        Funcion.setText("Añadir puertos de conexión adicionales a la placa base de tu computadora.");
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/sata.png")));
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        jlblNomPie.setText("");
        Concepto.setText("");
        Funcion.setText("");
        jlblNomPie.setText("Tarjeta de Video(GPU)");
        Concepto.setText("Memoria de trabajo a corto plazo de tus dispositivos.");
        Funcion.setText("Almacenar temporalmente datos de los programas que se están usando.");
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gpu.png")));
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        jlblNomPie.setText("");
        Concepto.setText("");
        Funcion.setText("");
        jlblNomPie.setText("Tarjeta de Red");
        Concepto.setText("Es un componente de hardware que conecta tu dispositivo a una red.");
        Funcion.setText("Conectar tu dispositivo a una red informática e Internet.");
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/red.png")));
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
        jlblNomPie.setText("");
        Concepto.setText("");
        Funcion.setText("");
        jlblNomPie.setText("Cooler del Procesador");
        Concepto.setText("Es el sistema de enfriamiento de la CPU. ");
        Funcion.setText("Disipar y extraer el calor extremo que genera la CPU durante su funcionamiento");
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/proc.png")));
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
        jlblNomPie.setText("");
        Concepto.setText("");
        Funcion.setText("");
        jlblNomPie.setText("Tarjeta de sonido");
        Concepto.setText("Componente que procesa y gestiona la entrada y salida del audio.");
        Funcion.setText("Procesar y convertir señales de audio.");
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/sonido.png")));
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        // TODO add your handling code here:
        jlblNomPie.setText("");
        Concepto.setText("");
        Funcion.setText("");
        jlblNomPie.setText("Batería CMOS");
        Concepto.setText("Es una pequeña pila de botón en la placa base de una computadora.");
        Funcion.setText("Mantener guardados los ajustes de hardware.");
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cmos.png")));
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        // TODO add your handling code here:
        jlblNomPie.setText("");
        Concepto.setText("");
        Funcion.setText("");
        jlblNomPie.setText("Cable de Administración");
        Concepto.setText("Es un cable especial para conectarse directamente a un puerto de consola.");
        Funcion.setText("Conectar directamente un equipo al puerto de gestión de un dispositivo de red.");
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cables.png")));
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        // TODO add your handling code here:
        jlblNomPie.setText("");
        Concepto.setText("");
        Funcion.setText("");
        jlblNomPie.setText("BIOS/UEFI");
        Concepto.setText("Es un pequeño programa fundamental guardado en un chip de la placa base de una computadora");
        Funcion.setText("Despertar y comprobar todos los componentes físicos y, a continuación, iniciar el sistema operativo");
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bios.png")));
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new jfrmSoporte().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Concepto;
    private javax.swing.JLabel Funcion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlblNomPie;
    // End of variables declaration//GEN-END:variables
}
